language: go

matrix:
  include:
    - go: 1.18.x
      env: GO111MODULE=on
    - go: 1.19.x
      env: GO111MODULE=on
    - go: 1.20.x
      env: GO111MODULE=on

before_install:
  - go get -u golang.org/x/lint/golint
  - export CONSUL_VERSION=1.12.2
  - export CONSUL_DOWNLOAD_URL=https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip

install:
  - go mod download
  - export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"
  - wget ${CONSUL_DOWNLOAD_URL}
  - unzip ./consul_${CONSUL_VERSION}_linux_amd64.zip
  - cp ./consul ${GOPATH}/bin/consul

go_import_path: github.com/dmitriyGarden/consul-leader-election

script:
  - make lint
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
